"""
screenshot_maker.py — Screenshot capture automation for Koya Launcher
=====================================================================
Automates launching and capturing screenshots of Koya Launcher's
screens (Home, App Drawer, Settings) across multiple locales using ADB,
then calls google_play_prep.py to compile the final showcase cards.

Requirements:
  1. A connected Android device/emulator (with developer options & USB debugging enabled).
  2. The Koya app (com.lagosproject.koya) installed on the device.
  3. Python 3 and Pillow installed.

Run:  python3 screenshot_maker.py
"""

import subprocess
import time
import os
import sys

LANGS = ["en-US", "es-ES", "fr-FR"]
PACKAGE = "com.lagosproject.koya"
SRC_DIR = "screenshots"


def run_cmd(cmd):
    print(f"  → {cmd}")
    r = subprocess.run(cmd, shell=True, stdout=subprocess.PIPE,
                       stderr=subprocess.PIPE, text=True)
    if r.returncode != 0:
        print(f"    ⚠ stderr: {r.stderr.strip()}")
    return r.stdout.strip()


def check_adb():
    devices = run_cmd("adb devices").splitlines()
    # Filter out header and empty lines
    active_devices = [line for line in devices[1:] if line.strip() and "device" in line]
    if not active_devices:
        print("\n❌ ERROR: No Android devices/emulators connected via ADB.")
        print("   Please connect a device, verify 'adb devices' displays it, and try again.")
        print("   Note: The Feature Graphic banner can still be generated by running:")
        print("   python3 google_play_prep.py\n")
        return False
    return True


def screencap(path):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    # Capture screen directly to local path via ADB pipe
    run_cmd(f"adb shell screencap -p > {path}")
    print(f"    📸 Saved screenshot: {path}")
    time.sleep(0.8)


def capture_screenshots_for_lang(lang):
    print(f"\n{'='*60}")
    print(f"  AUTOMATING LOCALE: {lang}")
    print(f"{'='*60}")

    # Set app locale (Android 13+ cmd, falls back or works on compatible levels)
    run_cmd(f"adb shell cmd locale set-app-locales {PACKAGE} --locales {lang}")
    time.sleep(0.5)

    # Force stop app to clear stack
    run_cmd(f"adb shell am force-stop {PACKAGE}")
    time.sleep(1.0)

    # 1. Capture Home Activity
    print("  Launching HomeActivity...")
    run_cmd(f"adb shell am start -n {PACKAGE}/.HomeActivity")
    time.sleep(3.5)  # Wait for launcher to load clock & layouts
    screencap(f"{SRC_DIR}/{lang}/home_screenshot.png")

    # 2. Capture App Drawer (Swipe up from Home)
    print("  Opening AppDrawer via swipe gesture...")
    run_cmd("adb shell input swipe 540 1800 540 600 300")
    time.sleep(2.0)
    screencap(f"{SRC_DIR}/{lang}/drawer_screenshot.png")

    # Go back to home
    run_cmd("adb shell input keyevent 4")
    time.sleep(1.0)

    # 3. Capture Settings (Long press empty area on Home)
    print("  Opening Settings via long press gesture...")
    run_cmd("adb shell input swipe 540 1500 540 1500 1500")
    time.sleep(2.0)
    screencap(f"{SRC_DIR}/{lang}/settings_screenshot.png")

    # Go back to home
    run_cmd("adb shell input keyevent 4")
    time.sleep(1.0)


def main():
    print("=" * 60)
    print("  Koya Launcher — Screenshot Automation via ADB")
    print("=" * 60)

    # Wake up screen and unlock
    run_cmd("adb shell input keyevent KEYCODE_WAKEUP")
    run_cmd("adb shell input keyevent 82")

    if not check_adb():
        sys.exit(1)

    for lang in LANGS:
        try:
            capture_screenshots_for_lang(lang)
        except Exception as e:
            print(f"  ❌ Error capturing {lang}: {e}")

    print("\n✅ Screenshots capture completed.")
    print("Running google_play_prep.py to generate store composites...")
    
    # Run the image preparation script
    subprocess.run(["python3", "google_play_prep.py"])


if __name__ == "__main__":
    main()
